# Generated by Django 5.0.1 on 2024-01-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_categpry_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='categpry',
            new_name='category',
        ),
    ]
